# Generated by Django 5.1.3 on 2024-12-22 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
