# Generated by Django 5.1.3 on 2025-01-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_qty',
        ),
    ]
