# Generated by Django 5.1.3 on 2025-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_cart_product_remove_cart_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
