# Generated by Django 5.1.3 on 2025-01-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cartitems_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product_qty',
            field=models.IntegerField(),
        ),
    ]
