# Generated by Django 5.1.3 on 2025-01-22 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='original_price',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='products',
            name='sell_price',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='products',
            name='stock_quantity',
            field=models.IntegerField(default=0, editable=False, help_text='Current quantity of the product available for sale (auto-updated).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
