# Generated by Django 5.1.3 on 2025-01-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_products_price_products_original_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='total_quantity',
        ),
    ]
