# Generated by Django 5.1.3 on 2025-01-23 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_category_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sell_price',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
