# Generated by Django 5.1.3 on 2025-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
