# Generated by Django 5.1.3 on 2025-01-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_cart_cartitems_order_orderitem_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='district',
            new_name='country',
        ),
    ]
