"""
Django settings for otakurealm project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5ukwy^4a4y)k_c-)*41%5*!2ln)n@0ggk@o!%v!tov2ff&9w!='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tinymce',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paypal.standard.ipn',
    'django_extensions',
    #other apps
    #Custom Apps
    'accounts',
    'store',
    'reviews',
]
""" 'dal',  # django-autocomplete-light
    'dal_select2',
    'easy_thumbnails',
    'filer', """                #within installed apps later if needed

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'store.middlewares.CustomSessionCookieMiddleware',
]

ROOT_URLCONF = 'otakurealm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #custo, context processor so that category can be viewed in all pages
                'store.context_processors.category_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'otakurealm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_USER_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT':os.getenv('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')

STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]

MEDIA_URL='/media/'

MEDIA_ROOT=os.path.join(BASE_DIR,"media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#to change django administration layout
JAZZMIN_SETTINGS={
    'site_header':"The Painting Muse",
    'site_brand':"The Painting Muse",
    'site_logo':"img/logo.png",
    'copyright':"paintingmuse.com",
}


#email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'unxaun@gmail.com'
EMAIL_HOST_PASSWORD = 'wwweazaeyavfzind'
DEFAULT_FROM_EMAIL = 'no-reply@yourdomain.com'

ADMIN_EMAIL = 'unxaun@gmail.com'

# For the Admin side (you may want different expiration or settings)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 60 * 60 * 24  # Set for 1 day, adjust as needed
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists until expiry

# For User-side (also can be customized if needed)
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name for regular users


#paypal settings
#set sandbox to true
PAYPAL_TEST=True
PAYPAL_RECEIVER_EMAIL="unxaun@gmail.com"    #business acc
PAYPAL_CLIENT_ID = 'AZLJNIQ6C5UHvhfOviGWLjgAoR9QYwW9QvElB3ZJBG8YUWPqbjQbqpvo1SiYvnoGqaNWkN7sWfo6zIin'
PAYPAL_CLIENT_SECRET = 'ENhsSDu2l-_4iiFdjJoTvVtjvBZrjinysIfoXh3yvslsjsgR610Z1BJk4oUuJLvROCL5MDV4YnZ7kC7h'


